# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicalItem',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.IntegerField(blank=True, choices=[(0, '-----'), (10, 'Common'), (20, 'Uncommon'), (30, 'Rare'), (40, 'Very Rare'), (50, 'Legendary'), (60, 'Artifact')], default=10, null=True, verbose_name='Item Rarity')),
                ('attunement', models.CharField(blank=True, choices=[(None, '-----'), ('Yes', 'Yes'), ('No', 'No'), ('Special', 'Special')], default='Yes', max_length=10, null=True, verbose_name='Requires Attunemnet')),
                ('type', models.IntegerField(blank=True, choices=[(0, '-----'), (100, 'Armor'), (200, 'Potion'), (300, 'Ring'), (400, 'Amulet'), (500, 'Rod'), (600, 'Scroll'), (700, 'Staff'), (800, 'Wand'), (900, 'Weapon'), (1000, 'Wonderous Item')], default=None, null=True, verbose_name='Item type')),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField()),
                ('benefits', djrichtextfield.models.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
