# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=100)),
                ('attunemnet', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
            ],
        ),
    ]
