# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 18:24
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicalitem',
            name='benefits',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
