# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicalitem',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
